### ISSUE TITLE
Is dinghy necessary?

### ISSUE THREAD

**Issue by samhavens** [mycargus/docker-grid-nightwatch#2]
I understand that it speeds things up on macOS, but given than Docker for Mac exists, is dinghy a required dependency or just recommended?

**Comment by mycargus** [comment]
Hello! Good question. No, dinghy isn't a required dependency. I simply prefer it over Docker for Mac (for now at least).

I'll update the project README to clarify this. Thanks for asking!

**Comment by samhavens** [comment]
Thank you! I am happy to open a PR with a documentation change.
